### ISSUE TITLE
about the visualization

### ISSUE THREAD

**Issue by caijianghe** [prs-eth/Diffusion-Super-Resolution#12]
Hello,dear author, I have some questions about visualization. for the residual plots, how can I ensure that vmax and vmin are centered around 0?
the following is my code, but the visualization results do not quite match what is shown in your paper.

vvmin = -np.max(np.abs(residual))
vvmax = np.max(np.abs(residual))
plt.imsave(os.path.join(root_residual, f'{idx}_{dxi}.png'), residual, cmap='RdBu', vmin=vvmin, vmax= vvmax)

**Comment by nandometzger** [comment]
Hi,
you need to assure that abs(vvmin)==abs(vvmax), otherwise the colormap is not symmetrical around zero.

if (-vvmin)>vmax:
    vmax = -vvmin
else:
    vvmin = -vvmax
    
also I recommend working with 95 or 98 [percentil](https://numpy.org/doc/stable/reference/generated/numpy.percentile.html) or similar since min max is not robust to outliers.

**Comment by caijianghe** [comment]
Thank you very much for receiving your reply
