### ISSUE TITLE
why the mae and the mse so small 

### ISSUE THREAD

**Issue by 1774537072** [prs-eth/Diffusion-Super-Resolution#6]
I do not quite understand the index, why depth graph *1000 was greatly standardized when data was loaded, and mae and mse were converted to "cm" at last, which seems to be different from the calculation method of other papers in this direction, could you please explain? Thank you very much indeed

**Comment by nandometzger** [comment]
Hi,

We ran all comparison methods ourselves to ensure the same evaluation protocol was used. The evaluation was designed by the authors of the LGR paper (https://openaccess.thecvf.com/content/CVPR2022/html/de_Lutio_Learning_Graph_Regularisation_for_Guided_Super-Resolution_CVPR_2022_paper.html), which was the previous SOTA method.

Since there was already a similar about this in #3:
Please note, that depth information is unnormalized by multiplying by the standard deviation **and** converted to cm and cm^2 here: https://github.com/prs-eth/Diffusion-Super-Resolution/blob/0f5cdaa372ac6eba77d57d2d9c2a1864617b05ed/run_eval.py#L119

Best
Nando
